const
  OAS_PATHS_DEFAULT_DIR_NAME = 'paths',
  OAS_SCHEMAS_DEFAULT_DIR_NAME = 'schemas',
  OAS_PARAMETERS_DEFAULT_DIR_NAME = 'params';

export {
  OAS_PATHS_DEFAULT_DIR_NAME,
  OAS_SCHEMAS_DEFAULT_DIR_NAME,
  OAS_PARAMETERS_DEFAULT_DIR_NAME,
};
